# Generated by Django 6.0.5 on 2026-05-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.services'),
        ),
    ]
