# Generated by Django 6.0.5 on 2026-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_services_remove_lineitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
