# Generated by Django 6.0.5 on 2026-06-06 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_bank_details_invoice_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual / Freelancer'), ('COMPANY', 'Registered Company')], default='INDIVIDUAL', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('account_number', models.CharField(default='', max_length=50)),
                ('ifsc_code', models.CharField(default='', max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
