# Generated by Django 6.0.5 on 2026-06-27 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=10)),
                ('next_issue_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.IntegerField(blank=True, null=True)),
                ('completed_occurrences', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
