# Generated by Django 6.0.5 on 2026-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_aiauditlog_chatmessage_pendingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
