# Generated by Django 6.0.5 on 2026-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_alter_payment_payment_method_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='swiftpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='swiftpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('SWIFTPAY', 'SwiftPay')], default='RAZORPAY', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='swiftpay_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='swiftpay_key_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('NEFT', 'NEFT/RTGS/IMPS'), ('RAZORPAY', 'Razorpay'), ('SWIFTPAY', 'SwiftPay')], default='NEFT', max_length=20),
        ),
    ]
